import { Memo } from "../types/memo";

const CURRENT_USER_ID = "Shitanshu";

export const MOCK_MEMOS: Memo[] = [
  {
    id: "1",
    sender: { id: "99", name: "Captain Sarah Jenkins", role: "Pilot" },
    recipients: [{ id: CURRENT_USER_ID, name: "Shitanshu", role: "Engineer" }],
    subject: "Flight Safety Protocol Update",
    content:
      "Please review the attached PDF regarding the new safety protocols.",
    priority: "High",
    flightNumber: "AI-302",
    isRead: false,
    isImportant: true,
    isDraft: false,
    isAcknowledged: false,
    requiresAcknowledgement: true,
    createdAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: "2",
    sender: { id: "98", name: "Mike Ross", role: "Co-Pilot" },
    recipients: [{ id: CURRENT_USER_ID, name: "Shitanshu", role: "Engineer" }],
    subject: "Weekly Maintenance Report",
    content: "No major issues found this week.",
    priority: "Medium",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isAcknowledged: true,
    requiresAcknowledgement: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    attachments: [],
  },
  {
    id: "3",
    sender: { id: CURRENT_USER_ID, name: "Shitanshu", role: "Engineer" },
    recipients: [],
    subject: "Request for spare parts",
    content: "I need to order 3 new turbine blades for...",
    priority: "Low",
    isRead: true,
    isImportant: false,
    isDraft: true,
    isAcknowledged: false,
    requiresAcknowledgement: false,
    createdAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: "4",
    sender: { id: CURRENT_USER_ID, name: "Shitanshu", role: "Engineer" },
    recipients: [],
    subject: "Shift change request",
    content: "Looking to swap shifts next Tuesday.",
    priority: "Low",
    isRead: true,
    isImportant: false,
    isDraft: true,
    isAcknowledged: false,
    requiresAcknowledgement: false,
    createdAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: "5",
    sender: { id: CURRENT_USER_ID, name: "Shitanshu", role: "Engineer" },
    recipients: [{ id: "99", name: "Captain Sarah", role: "Pilot" }],
    subject: "Engine Inspection Complete",
    content: "The inspection for Engine 2 is complete. All green.",
    priority: "High",
    isRead: true,
    isImportant: false,
    isDraft: false,
    isAcknowledged: false,
    requiresAcknowledgement: true,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    attachments: [],
  },
];
