import { CompletedCheckItem } from "../components/SpotCheck/CompletedCheckListItem";

export const MOCK_COMPLETE_CHECKS: CompletedCheckItem[] = [
  {
    id: "1",
    flight: "WY225",
    route: "MCT-COK",
    departure: "12 01",
    galley: "G1",
    stowage: "103F",
    category: "Atlas Half Size Meal Cart",
    carrier: "B737 Holloware ISC-MEA",
    status: "Pass",
    name: "John Doe",
    info: "Clean and ready",
    time: "10:30 AM",
  },
  {
    id: "2",
    flight: "WY225",
    route: "MCT-COK",
    departure: "12 01",
    galley: "G2",
    stowage: "205TF",
    category: "Atlas Small Unit Aluminum",
    carrier: "JC Dry store NB",
    status: "Pass",
    name: "Jane Smith",
    info: "All items present",
    time: "11:15 AM",
  },
  {
    id: "3",
    flight: "WY225",
    route: "MCT-COK",
    departure: "12 01",
    galley: "G3",
    stowage: "401A",
    category: "Atlas Full Size Trolley",
    carrier: "Standard Unit",
    status: "Fail",
    name: "Bob Wilson",
    info: "Missing 2 full size trolleys",
    time: "12:00 PM",
  },
];
